### ISSUE TITLE
Dockerize the Development Environment

### ISSUE THREAD

**Issue by Gauntlet173** [Blawx/blawx#21]
It would be great if we could dockerize the app for the purpose of fcilitating development and deployment.

Eventually, it should be structured with more than one container, to allow each to grow as required. But for now, if we could just get the single-machine installation process streamlined that would be a big win.

**Comment by shiv-io** [comment]
Happy to work on this!

Is it safe to base the Dockerfile on the installation instructions provided at https://github.com/Blawx/blawx/blob/master/INSTALL.md?

**Comment by Gauntlet173** [comment]
Fantastic, thanks, Shiv!

That is the most up-to-date version of the installation process I have, yes. I don't know about "safe", but that's as close as you're going to get, right now. :)

And I'm not going to be playing with any issues that would modify the installation process for a while.

It does work for me relatively painlessly under WSL2 on Windows 10/Ubuntu.

If you run into any problems with it, let me know. I'll help however I can. More than likely it will be an issue where Flora-2 is not able to create the required temporary files, and you need to run it as root. See issue #11.

Thanks again. Excited to see how it works!

**Comment by Gauntlet173** [comment]
Great stuff, Shiv. Just tested it on my WIndows 10/WSL2/Ubuntu device and it works perfectly. Thanks so much.

**Comment by shiv-io** [comment]
Happy to help, Jason!

**Comment by Gauntlet173** [comment]
Hi again, Shiv: Quick question for you. I'm very new to Docker, so let me know if I'm getting it wrong.

It seems to me like if you git clone a version of blockly down to your machine, and then build, the Dockerfile tells it to git clone dev inside the container and use those files. Which is fine if what you want to do is run the current dev version, but you're cloning it twice for no reason, and it doesn't work if you want to run a different branch (master, or a branch you are working on), because it always grabs dev.

Also, because it does a git clone against dev inside the container, any changes you make to the branch you cloned outside the container won't be reflected in the container unless you manually copy them in, which sort of defeats the point.

Could you modify it so that it doesn't repeat the git clone of blawx, and instead uses COPY commands? And in order to decrease build times by taking advantage of caching, could we put the COPY commands at the end of the Dockerfile?

Also, is there a way to modify the way we pull in blockly so that it won't get cloned again if it hasn't changed? I don't understand how dependencies work, obvously.

**Comment by shiv-io** [comment]
Hey Jason,

You bring up some really good points. I’m going to look into this a little more over the weekend and write back with comments and probably add another commit with changes for you to review. 

Cheers,
Shiv

**Comment by Gauntlet173** [comment]
Thanks so much, Shiv. Let me know.
