### ISSUE TITLE
Dockerfile: Add COPY commands to avoid having to clone blawx twice

### ISSUE THREAD

**Issue by shiv-io** [Blawx/blawx#34]
The Dockerfile currently clones blawx inside the Docker container. Instead, we want to make it so users can first `git clone https://github.com/Blawx/blawx.git` and run `docker build -t blawx .` without the Dockerfile telling Docker to `git clone blawx` inside the container. Instead, the Dockerfile should use `COPY` to copy the cloned blawx repo into the container.

**Comment by shiv-io** [comment]
Assigning this to myself, @Gauntlet173! (unable to do so on the sidebar)

**Comment by Gauntlet173** [comment]
I pulled #36 to dev, and it seems to be working.

**Comment by shiv-io** [comment]
Awesome!
