### ISSUE TITLE
Add package.json for npm dependency management

### ISSUE THREAD

**Issue by shiv-io** [Blawx/blawx#35]
We should add a `package.json` to the repository for npm dependency management. This will help optimize Docker builds so `npm install blockly xmlhttprequest` can be replaced with `npm install`. 

`npm install` will look at `package.json` to determine if any packages have been updated and only install/updated the dependencies if so.

I'm definitely not an expert with npm dependencies, so please feel free to correct me here if I'm wrong anywhere.

(self-assigning this @Gauntlet173!)

`npm init` reference: https://docs.npmjs.com/cli/init

**Comment by Gauntlet173** [comment]
v1 no longer relies on node.
